
[functions.teacher-sso]
verify_jwt = false

[functions.get-teacher-apps]
verify_jwt = false

[functions.mint-teacher-sso]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.bulk-create-students]
verify_jwt = false

[functions.delete-student]
verify_jwt = false

[functions.delete-teacher-account]
verify_jwt = false

[functions.student-sso]
verify_jwt = false

[functions.ai-module-assist]
verify_jwt = false

[functions.get-ai-usage]
verify_jwt = false

[functions.sync-classes]
verify_jwt = false
